/**
 * Shared TypeScript types for the Cosailor Insights frontend.
 *
 * These interfaces mirror the backend Pydantic models so the compiler can
 * catch shape mismatches between API responses and UI components at build time.
 */

/** A single contractor lead row as returned by GET /api/leads and GET /api/leads/:id. */
export interface Lead {
  id: string;
  company_name: string;
  city: string | null;
  state: string | null;
  postal_code: string | null;
  country_code: string;
  phone: string | null;
  website: string | null;
  certifications: string[];
  rating: number | null;
  review_count: number | null;
  /** Raw Perplexity research text stored after Stage 2 of the pipeline. */
  research_summary: string | null;
  /** AI quality score on a 1–10 scale; null until the lead is enriched. */
  lead_score: number | null;
  score_rationale: string | null;
  /** Likelihood-to-convert score on a 1–10 scale; null until enriched. */
  convertibility_score: number | null;
  convertibility_rationale: string | null;
  /** Straight-line distance from the search ZIP code. */
  distance_miles: number | null;
  /** Bucketed distance label used to compute the priority modifier. */
  distance_band: 'near' | 'mid' | 'far' | null;
  /** Composite rank: (lead_score + convertibility_score) / 2 × distance modifier. */
  priority_index: number | null;
  /** Two-to-three sentence Claude summary for the lead card. */
  ai_summary: string | null;
  /** Up to three sales talking points generated by Claude. */
  talking_points: string[];
  recommended_approach: string | null;
  /** Pipeline stage the lead is currently in. */
  status: 'scraped' | 'researched' | 'enriched' | 'failed';
  error_message: string | null;
  enriched_at: string | null;
  created_at: string;
}

/** Paginated response from GET /api/leads. */
export interface PaginatedLeadsResponse {
  leads: Lead[];
  total: number;
  page: number;
  limit: number;
}

/** Immediate 202 response returned by POST /api/pipeline/run. */
export interface PipelineRunResponse {
  run_id: string;
  status: string;
  message: string;
}

/** Current state of a pipeline run, returned by GET /api/pipeline/status/:run_id and /latest. */
export interface PipelineStatusResponse {
  run_id: string;
  /** 'running' while the background task is active; terminal states are 'completed' or 'failed'. */
  status: 'running' | 'completed' | 'failed';
  leads_scraped: number;
  leads_enriched: number;
  started_at: string;
  finished_at: string | null;
  error_message: string | null;
  /** Original params — used by the frontend to pre-fill the retry form. */
  postal_code: string;
  country_code: string;
  distance: number;
}
